name: Deploy to App Engine

on:
  push:
    branches:
      - main

workflow_dispatch:


env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west3

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY_JSON }}
        export_default_credentials: true  

    - name: Deploy
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        deliverables: app.yaml
        version: v1
        project_id: ${{ env.PROJECT_ID }}
        credentials: ${{ secrets.GCP_SA_KEY_JSON }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
