name: Deploy to App Engine

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west3

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, 'deploy')"
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY_JSON }}'

    - name: Deploy
      id: deploy
      uses: google-github-actions/deploy-appengine@v0
      with:
        deliverables: app.yaml
        version: v1

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
